### ISSUE TITLE
combine_reanalysis_data.pl bug

### ISSUE THREAD

**Issue by JoshWiejaczka** [geoscience-community-codes/tephra2#3]
Running the perl script "combine_reanalysis_data.pl" produces output files with all zeros for height, windspeed, and direction.

**Comment by ljc-geo** [comment]
Hello,
Yes, I had the same problem. I think something changed with the REANALYsis data. I made some changes to the perl script  and was able to make the script work again. Let me locate the revised script and I will send it to you.

Cheers,

Laura Connor
Research Associate
813-334-0546 (mobile)

School of Geosciences​
University of South Florida
Tampa, Florida 33620


________________________________

**Comment by ljc-geo** [comment]
Hi,
I updated the perl script used to create a wind database from NOAA REANALYSIS data files. It should no longer give only zeros. Let me know if you have any difficulties.

https://github.com/geoscience-community-codes/tephra2/blob/master/plotting_scripts/combine_reanalysis_data.pl
[https://avatars.githubusercontent.com/u/15144615?s=400&v=4]<https://github.com/geoscience-community-codes/tephra2/blob/master/plotting_scripts/combine_reanalysis_data.pl>
geoscience-community-codes/tephra2<https://github.com/geoscience-community-codes/tephra2/blob/master/plotting_scripts/combine_reanalysis_data.pl>
Tephra2 is a tephra dispersion simulation tool, used to estimate the mass of tephra that will accumulate at a site or over a region, given explosive eruption conditions. - geoscience-community-code...
github.com


Laura Connor
Research Associate
813-334-0546 (mobile)

School of Geosciences​
University of South Florida
Tampa, Florida 33620


________________________________

**Comment by JoshWiejaczka** [comment]
Works like a charm, thanks for the update!
